### ISSUE TITLE
The necessary package metabolieIDmapping is not installed

### ISSUE THREAD

**Issue by hnakahara** [yigbt/multiGSEA#1]
I followed the steps in the workflow(https://bioconductor.org/packages/devel/bioc/vignettes/multiGSEA/inst/doc/multiGSEA.html), but I got an error with the following command.

pathways <- getMultiOmicsFeatures( dbs = databases, layer = layers,
                                   returnTranscriptome = "SYMBOL",
                                   returnProteome = "SYMBOL",
                                   returnMetabolome = "HMDB")

The necessary package metabolieIDmapping is not installed.

Using Bioconductor and local folder which downloaded "metaboliteIDmapping_0.99.7.tar.gz" I tried to install metabolieIDmapping, but I was unable to do so.

Is there any way to solve this problem?

**Comment by boll3** [comment]
Does this issue persist?

I'm not able to reproduce your problem.
In a clean R (v4.0.2) installation, I am able to install both package multiGSEA and metaboliteIDmapping without problems.

For both package I used the commands as given on the bioconductor page:
BiocManager::install("multiGSEA")
BiocManager::install("metaboliteIDmapping")

**Comment by nakanaka439** [comment]
Thanks for the answer.
I was using R4.0.0.0 so I updated to R4.0.2 and reinstalled it and the problem was resolved.
Thank you for your great work.

**Comment by hnakahara** [comment]
Thanks for the answer.
I was using R4.0.0.0 so I updated to R4.0.2 and reinstalled it and the problem was resolved.
Thank you for your great work.
