### ISSUE TITLE
Why combine padj rather than pvalue

### ISSUE THREAD

**Issue by huerqiang** [yigbt/multiGSEA#5]
Hi! I am learning your R package. I would like to consult why you choose the adjusted pvalue to combine rather than the original pvalue: https://github.com/yigbt/multiGSEA/blob/master/R/enrichment_functions.R#L156

After all, the subsequent steps will adjust the combined pvalue:
```r
df$combined_pval <- combinePvalues( df)
df$combined_padj <- p.adjust( df$combined_pval, method = "BH")
```

**Comment by boll3** [comment]
P-values are now combined by default without prior adjustment.
To reproduce the original behavior, use `col_pattern = "padj"` in the `combinePvalues()` function.
This has been effective since Bioconductor RELEASE 3.18
